/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Tesseral from "../../../../../api/index";
import * as core from "../../../../../core";

export const AuthenticateApiKeyRequest: core.serialization.Schema<
    serializers.AuthenticateApiKeyRequest.Raw,
    Tesseral.AuthenticateApiKeyRequest
> = core.serialization.object({
    secretToken: core.serialization.string().optional(),
});

export declare namespace AuthenticateApiKeyRequest {
    export interface Raw {
        secretToken?: string | null;
    }
}
