/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface SessionsListSessionsRequest {
    /**
     * The User ID.
     */
    userId?: string;
    /**
     * A pagination token. Leave empty to get the first page of results.
     */
    pageToken?: string;
}
