/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * AuditLogEvent represents a record in the Project's audit log.
 */
export interface AuditLogEvent {
    /** The Audit Log Event ID. Starts with `audit_log_event_...`. */
    id?: string;
    /** The Organization the event occurred within, if any. */
    organizationId?: string;
    /** The User that performed the event, if any. */
    actorUserId?: string;
    /** The Session that performed the event, if any. */
    actorSessionId?: string;
    /** The API Key that performed the event, if any. */
    actorApiKeyId?: string;
    /** The Backend API key that performed the event, if any. */
    actorBackendApiKeyId?: string;
    /** The Intermediate Session that performed the action, if any. */
    actorIntermediateSessionId?: string;
    /** When the event occurred. */
    eventTime?: Date;
    /** The name of the event. */
    eventName?: string;
    /** The event payload JSON. */
    eventDetails?: Record<string, unknown>;
    /**
     * Credentials for the actor performing the action. Input-only.
     *
     *  Can be used as a shorthand for actor information when calling CreateAuditLogEvent.
     */
    actorCredentials?: string;
}
