/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface CreateSamlConnectionResponse {
    /** The created SAML Connection. */
    samlConnection?: Tesseral.SamlConnection;
}
