/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface CreateOrganizationResponse {
    /** The Organization to create. */
    organization?: Tesseral.Organization;
}
