/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface CreateUserResponse {
    /** The created User. */
    user?: Tesseral.User;
}
