/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface GetOidcConnectionResponse {
    /** The requested OIDC Connection. */
    oidcConnection?: Tesseral.OidcConnection;
}
