/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface GetOrganizationGoogleHostedDomainsResponse {
    /** The Organization's Google Hosted Domains. */
    organizationGoogleHostedDomains?: Tesseral.OrganizationGoogleHostedDomains;
}
