/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface GetOrganizationDomainsResponse {
    /** The requested Organization Domains. */
    organizationDomains?: Tesseral.OrganizationDomains;
}
