/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface GetProjectResponse {
    /** The requested Project. */
    project?: Tesseral.Project;
}
