/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * OIDCConnection represents an OpenID Connect configuration for an Organization.
 */
export interface OidcConnection {
    /** The OIDC Connection ID. Starts with `oidc_connection_...`. */
    id?: string;
    /** The Organization this OIDC Connection belongs to. */
    organizationId?: string;
    /** When the OIDC Connection was created. */
    createTime?: Date;
    /** When the OIDC Connection was last updated. */
    updateTime?: Date;
    /** Whether this is the primary OIDC Connection for the Organization. */
    primary?: boolean;
    /** The OIDC Provider's configuration URL. */
    configurationUrl?: string;
    /** The OIDC Provider's Client ID. */
    clientId?: string;
    /**
     * The OIDC Provider's Client Secret.
     *  This field is write-only.
     */
    clientSecret?: string;
    /** The OIDC Provider's redirect URI. */
    redirectUri?: string;
}
