/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An Organization represents one of your corporate customers.
 */
export interface Organization {
    /** The Organization ID. Starts with `org_...`. */
    id?: string;
    /** A human-friendly name for the Organization. */
    displayName?: string;
    /** When the Organization was created. */
    createTime?: Date;
    /** When the Organization was last updated. */
    updateTime?: Date;
    /** Whether the Organization supports "Log in with Google". */
    logInWithGoogle?: boolean;
    /** Whether the Organization supports "Log in with Microsoft". */
    logInWithMicrosoft?: boolean;
    /** Whether the Organization supports Log in with GitHub. */
    logInWithGithub?: boolean;
    /** Whether the Organization supports "Log in with email". */
    logInWithEmail?: boolean;
    /** Whether the Organization supports "Log in with password". */
    logInWithPassword?: boolean;
    /** Whether the Organization supports "Log in with SAML". */
    logInWithSaml?: boolean;
    /** Whether the Organization supports "Log in with OIDC". */
    logInWithOidc?: boolean;
    /** Whether the Organization supports authenticator apps as a secondary auth factor. */
    logInWithAuthenticatorApp?: boolean;
    /** Whether the Organization supports passkeys as a secondary auth factor. */
    logInWithPasskey?: boolean;
    /** Whether the Organization requires a secondary auth factor. */
    requireMfa?: boolean;
    /** Whether the Organization has SCIM enabled. */
    scimEnabled?: boolean;
    /** Whether the Organization's Users can create Organization-specific Roles. */
    customRolesEnabled?: boolean;
    /** Whether API Keys are enabled for the Organization. */
    apiKeysEnabled?: boolean;
}
