/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * OrganizationDomains defines the domains associated with an Organization.
 */
export interface OrganizationDomains {
    /** The ID of the Organization. */
    organizationId?: string;
    /**
     * A list of domains associated with the organization.
     *
     *  When an Organization uses SAML or SCIM, only emails from this list are
     *  permitted.
     */
    domains?: string[];
}
