/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * OrganizationMicrosoftTenantIDs represents the Microsoft Tenant IDs ("TIDs")
 *  associated with an Organization.
 */
export interface OrganizationMicrosoftTenantIDs {
    /** The ID of the Organization. */
    organizationId?: string;
    /**
     * A list of Microsoft Tenant IDs associated with the organization.
     *
     *  These values correspond to Microsoft OAuth `tid` claims:
     *
     *  https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference
     */
    microsoftTenantIds?: string[];
}
