/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * OrganizationGoogleHostedDomains represents the Google Hosted Domains ("HDs")
 *  associated with an Organization.
 */
export interface OrganizationGoogleHostedDomains {
    /** The ID of the Organization. */
    organizationId?: string;
    /**
     * A list of Google-hosted domains associated with the organization.
     *
     *  These values correspond to Google OAuth `hd` claims:
     *
     *  https://developers.google.com/identity/openid-connect/openid-connect#obtainuserinfo
     */
    googleHostedDomains?: string[];
}
