/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Passkey represents a WebAuthn public key credential registered by a User.
 */
export interface Passkey {
    /** The Passkey ID. Starts with `passkey_...`. */
    id?: string;
    /** The User this Passkey belongs to. */
    userId?: string;
    /** The timestamp of when the Passkey was created. */
    createTime?: Date;
    /** The timestamp of when the Passkey was last updated. */
    updateTime?: Date;
    /** Indicates whether the Passkey is disabled. */
    disabled?: boolean;
    /** The unique credential ID for the Passkey, as a binary value. */
    credentialId?: string;
    /**
     * The public key associated with the Passkey, in PEM-encoded PKIX format.
     *
     *  Starts with `-----BEGIN PUBLIC KEY-----`.
     */
    publicKeyPkix?: string;
    /** The Authenticator Attestation GUID (AAGUID) for the Passkey. */
    aaguid?: string;
    /** The relying party ID associated with the Passkey. */
    rpId?: string;
}
