/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Project {
    id?: string;
    displayName?: string;
    createTime?: Date;
    updateTime?: Date;
    logInWithGoogle?: boolean;
    logInWithMicrosoft?: boolean;
    logInWithEmail?: boolean;
    logInWithPassword?: boolean;
    logInWithSaml?: boolean;
    logInWithAuthenticatorApp?: boolean;
    logInWithPasskey?: boolean;
    googleOauthClientId?: string;
    googleOauthClientSecret?: string;
    microsoftOauthClientId?: string;
    microsoftOauthClientSecret?: string;
    vaultDomain?: string;
    trustedDomains?: string[];
    redirectUri?: string;
    afterLoginRedirectUri?: string;
    afterSignupRedirectUri?: string;
    emailSendFromDomain?: string;
}
