/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * SAMLConnection represents a SAML configuration for an Organization.
 */
export interface SamlConnection {
    /** The SAML Connection ID. Starts with `saml_connection_...`. */
    id?: string;
    /** The Organization this SAML Connection belongs to. */
    organizationId?: string;
    /** When the SAML Connection was created. */
    createTime?: Date;
    /** When the SAML Connection was last updated. */
    updateTime?: Date;
    /** Whether this is the primary SAML Connection for the Organization. */
    primary?: boolean;
    /** The Service Provider Assertion Consumer Service (ACS) URL. */
    spAcsUrl?: string;
    /** The Service Provider Entity ID. */
    spEntityId?: string;
    /** The Identity Provider Redirect URL. */
    idpRedirectUrl?: string;
    /**
     * The Identity Provider certificate, in PEM-encoded X.509 format.
     *
     *  Starts with `----BEGIN CERTIFICATE----`.
     */
    idpX509Certificate?: string;
    /** The Identity Provider Entity ID. */
    idpEntityId?: string;
}
