/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScimapiKey {
    id?: string;
    organizationId?: string;
    createTime?: Date;
    updateTime?: Date;
    displayName?: string;
    secretToken?: string;
    revoked?: boolean;
}
