/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * SCIMAPIKey represents an API key for SCIM operations.
 */
export interface ScimapiKey {
    /** The SCIM API Key ID. Starts with `scim_api_key_...`. */
    id?: string;
    /** The Organization this SCIM API Key belongs to. */
    organizationId?: string;
    /** When the SCIM API Key was created. */
    createTime?: Date;
    /** When the SCIM API Key was last updated. */
    updateTime?: Date;
    /** A human-readable display name for this SCIM API Key. */
    displayName?: string;
    /** The secret token for this SCIM API Key. */
    secretToken?: string;
    /** Whether this SCIM API Key is revoked. */
    revoked?: boolean;
}
