/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents a Session for a logged-in User.
 */
export interface Session {
    /** The Session ID. Starts with `session_...`. */
    id?: string;
    /** The User this Session belongs to. */
    userId?: string;
    /** Whether the Session is revoked. */
    revoked?: boolean;
    /** When the Session was created. */
    createTime?: Date;
    /** When the Session was last active. */
    lastActiveTime?: Date;
    /** When the Session expires. */
    expireTime?: Date;
}
