/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Session {
    id?: string;
    userId?: string;
    revoked?: boolean;
    createTime?: Date;
    lastActiveTime?: Date;
    expireTime?: Date;
}
