/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface UpdateOrganizationMicrosoftTenantIDsResponse {
    /** The updated Microsoft Tenant IDs for the Organization. */
    organizationMicrosoftTenantIds?: Tesseral.OrganizationMicrosoftTenantIDs;
}
