/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface UpdateOrganizationResponse {
    /** The updated Organization. */
    organization?: Tesseral.Organization;
}
