/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface UpdatePasskeyResponse {
    /** The updated Passkey. */
    passkey?: Tesseral.Passkey;
}
