/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface UpdateOidcConnectionResponse {
    /** The updated OIDC Connection. */
    oidcConnection?: Tesseral.OidcConnection;
}
