/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface UpdateUserResponse {
    /** The updated User. */
    user?: Tesseral.User;
}
