/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Tesseral from "../index";

export interface UpdateOrganizationDomainsResponse {
    /** The updated Organization Domains. */
    organizationDomains?: Tesseral.OrganizationDomains;
}
