/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UserInvite {
    id?: string;
    organizationId?: string;
    createTime?: Date;
    updateTime?: Date;
    email?: string;
    owner?: boolean;
}
