/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * UserInvite represents an invitation for a User to join an Organization.
 */
export interface UserInvite {
    /** The User Invite ID. Starts with `user_invite_...`. */
    id?: string;
    /** The Organization this User Invite belongs to. */
    organizationId?: string;
    /** When the User Invite was created. */
    createTime?: Date;
    /** When the User Invite was last updated. */
    updateTime?: Date;
    /** The invitee's email address. */
    email?: string;
    /**
     * Indicates whether the invited User will have owner privileges in the
     *  Organization.
     */
    owner?: boolean;
}
