/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ScimApiKeysListScimapiKeysRequest {
    /**
     * The ID of the Organization.
     */
    organizationId?: string;
    /**
     * A pagination token. Leave empty to get the first page of results.
     */
    pageToken?: string;
}
