/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const AuthenticateApiKeyResponse: core.serialization.ObjectSchema<
    serializers.AuthenticateApiKeyResponse.Raw,
    Tesseral.AuthenticateApiKeyResponse
> = core.serialization.object({
    apiKeyId: core.serialization.string().optional(),
    organizationId: core.serialization.string().optional(),
    actions: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace AuthenticateApiKeyResponse {
    export interface Raw {
        apiKeyId?: string | null;
        organizationId?: string | null;
        actions?: string[] | null;
    }
}
