/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { AuditLogEvent } from "./AuditLogEvent";

export const CreateAuditLogEventResponse: core.serialization.ObjectSchema<
    serializers.CreateAuditLogEventResponse.Raw,
    Tesseral.CreateAuditLogEventResponse
> = core.serialization.object({
    auditLogEvent: AuditLogEvent.optional(),
});

export declare namespace CreateAuditLogEventResponse {
    export interface Raw {
        auditLogEvent?: AuditLogEvent.Raw | null;
    }
}
