/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { Organization } from "./Organization";

export const CreateOrganizationResponse: core.serialization.ObjectSchema<
    serializers.CreateOrganizationResponse.Raw,
    Tesseral.CreateOrganizationResponse
> = core.serialization.object({
    organization: Organization.optional(),
});

export declare namespace CreateOrganizationResponse {
    export interface Raw {
        organization?: Organization.Raw | null;
    }
}
