/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const DeleteOidcConnectionResponse: core.serialization.ObjectSchema<
    serializers.DeleteOidcConnectionResponse.Raw,
    Tesseral.DeleteOidcConnectionResponse
> = core.serialization.object({});

export declare namespace DeleteOidcConnectionResponse {
    export interface Raw {}
}
