/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const DeletePasskeyResponse: core.serialization.ObjectSchema<
    serializers.DeletePasskeyResponse.Raw,
    Tesseral.DeletePasskeyResponse
> = core.serialization.object({});

export declare namespace DeletePasskeyResponse {
    export interface Raw {}
}
