/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { OidcConnection } from "./OidcConnection";

export const GetOidcConnectionResponse: core.serialization.ObjectSchema<
    serializers.GetOidcConnectionResponse.Raw,
    Tesseral.GetOidcConnectionResponse
> = core.serialization.object({
    oidcConnection: OidcConnection.optional(),
});

export declare namespace GetOidcConnectionResponse {
    export interface Raw {
        oidcConnection?: OidcConnection.Raw | null;
    }
}
