/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { OrganizationDomains } from "./OrganizationDomains";

export const GetOrganizationDomainsResponse: core.serialization.ObjectSchema<
    serializers.GetOrganizationDomainsResponse.Raw,
    Tesseral.GetOrganizationDomainsResponse
> = core.serialization.object({
    organizationDomains: OrganizationDomains.optional(),
});

export declare namespace GetOrganizationDomainsResponse {
    export interface Raw {
        organizationDomains?: OrganizationDomains.Raw | null;
    }
}
