/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { OidcConnection } from "./OidcConnection";

export const ListOidcConnectionsResponse: core.serialization.ObjectSchema<
    serializers.ListOidcConnectionsResponse.Raw,
    Tesseral.ListOidcConnectionsResponse
> = core.serialization.object({
    oidcConnections: core.serialization.list(OidcConnection).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListOidcConnectionsResponse {
    export interface Raw {
        oidcConnections?: OidcConnection.Raw[] | null;
        nextPageToken?: string | null;
    }
}
