/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { Passkey } from "./Passkey";

export const ListPasskeysResponse: core.serialization.ObjectSchema<
    serializers.ListPasskeysResponse.Raw,
    Tesseral.ListPasskeysResponse
> = core.serialization.object({
    passkeys: core.serialization.list(Passkey).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListPasskeysResponse {
    interface Raw {
        passkeys?: Passkey.Raw[] | null;
        nextPageToken?: string | null;
    }
}
