/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { Session } from "./Session";

export const ListSessionsResponse: core.serialization.ObjectSchema<
    serializers.ListSessionsResponse.Raw,
    Tesseral.ListSessionsResponse
> = core.serialization.object({
    sessions: core.serialization.list(Session).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListSessionsResponse {
    export interface Raw {
        sessions?: Session.Raw[] | null;
        nextPageToken?: string | null;
    }
}
