/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const OidcConnection: core.serialization.ObjectSchema<serializers.OidcConnection.Raw, Tesseral.OidcConnection> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        organizationId: core.serialization.string().optional(),
        createTime: core.serialization.date().optional(),
        updateTime: core.serialization.date().optional(),
        primary: core.serialization.boolean().optional(),
        configurationUrl: core.serialization.string().optional(),
        clientId: core.serialization.string().optional(),
        clientSecret: core.serialization.string().optional(),
        redirectUri: core.serialization.string().optional(),
    });

export declare namespace OidcConnection {
    export interface Raw {
        id?: string | null;
        organizationId?: string | null;
        createTime?: string | null;
        updateTime?: string | null;
        primary?: boolean | null;
        configurationUrl?: string | null;
        clientId?: string | null;
        clientSecret?: string | null;
        redirectUri?: string | null;
    }
}
