/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const OrganizationGoogleHostedDomains: core.serialization.ObjectSchema<
    serializers.OrganizationGoogleHostedDomains.Raw,
    Tesseral.OrganizationGoogleHostedDomains
> = core.serialization.object({
    organizationId: core.serialization.string().optional(),
    googleHostedDomains: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace OrganizationGoogleHostedDomains {
    export interface Raw {
        organizationId?: string | null;
        googleHostedDomains?: string[] | null;
    }
}
