/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const OrganizationMicrosoftTenantIDs: core.serialization.ObjectSchema<
    serializers.OrganizationMicrosoftTenantIDs.Raw,
    Tesseral.OrganizationMicrosoftTenantIDs
> = core.serialization.object({
    organizationId: core.serialization.string().optional(),
    microsoftTenantIds: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace OrganizationMicrosoftTenantIDs {
    interface Raw {
        organizationId?: string | null;
        microsoftTenantIds?: string[] | null;
    }
}
