/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";

export const Project: core.serialization.ObjectSchema<serializers.Project.Raw, Tesseral.Project> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        displayName: core.serialization.string().optional(),
        createTime: core.serialization.date().optional(),
        updateTime: core.serialization.date().optional(),
        logInWithGoogle: core.serialization.boolean().optional(),
        logInWithMicrosoft: core.serialization.boolean().optional(),
        logInWithEmail: core.serialization.boolean().optional(),
        logInWithPassword: core.serialization.boolean().optional(),
        logInWithSaml: core.serialization.boolean().optional(),
        logInWithAuthenticatorApp: core.serialization.boolean().optional(),
        logInWithPasskey: core.serialization.boolean().optional(),
        googleOauthClientId: core.serialization.string().optional(),
        googleOauthClientSecret: core.serialization.string().optional(),
        microsoftOauthClientId: core.serialization.string().optional(),
        microsoftOauthClientSecret: core.serialization.string().optional(),
        vaultDomain: core.serialization.string().optional(),
        trustedDomains: core.serialization.list(core.serialization.string()).optional(),
        redirectUri: core.serialization.string().optional(),
        afterLoginRedirectUri: core.serialization.string().optional(),
        afterSignupRedirectUri: core.serialization.string().optional(),
        emailSendFromDomain: core.serialization.string().optional(),
    });

export declare namespace Project {
    interface Raw {
        id?: string | null;
        displayName?: string | null;
        createTime?: string | null;
        updateTime?: string | null;
        logInWithGoogle?: boolean | null;
        logInWithMicrosoft?: boolean | null;
        logInWithEmail?: boolean | null;
        logInWithPassword?: boolean | null;
        logInWithSaml?: boolean | null;
        logInWithAuthenticatorApp?: boolean | null;
        logInWithPasskey?: boolean | null;
        googleOauthClientId?: string | null;
        googleOauthClientSecret?: string | null;
        microsoftOauthClientId?: string | null;
        microsoftOauthClientSecret?: string | null;
        vaultDomain?: string | null;
        trustedDomains?: string[] | null;
        redirectUri?: string | null;
        afterLoginRedirectUri?: string | null;
        afterSignupRedirectUri?: string | null;
        emailSendFromDomain?: string | null;
    }
}
