/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { OrganizationDomains } from "./OrganizationDomains";

export const UpdateOrganizationDomainsResponse: core.serialization.ObjectSchema<
    serializers.UpdateOrganizationDomainsResponse.Raw,
    Tesseral.UpdateOrganizationDomainsResponse
> = core.serialization.object({
    organizationDomains: OrganizationDomains.optional(),
});

export declare namespace UpdateOrganizationDomainsResponse {
    export interface Raw {
        organizationDomains?: OrganizationDomains.Raw | null;
    }
}
