/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Tesseral from "../../api/index";
import * as core from "../../core";
import { OidcConnection } from "./OidcConnection";

export const UpdateOidcConnectionResponse: core.serialization.ObjectSchema<
    serializers.UpdateOidcConnectionResponse.Raw,
    Tesseral.UpdateOidcConnectionResponse
> = core.serialization.object({
    oidcConnection: OidcConnection.optional(),
});

export declare namespace UpdateOidcConnectionResponse {
    export interface Raw {
        oidcConnection?: OidcConnection.Raw | null;
    }
}
