/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Organizations } from "./api/resources/organizations/client/Client";
import { Passkeys } from "./api/resources/passkeys/client/Client";
import { Projects } from "./api/resources/projects/client/Client";
import { SamlConnections } from "./api/resources/samlConnections/client/Client";
import { ScimApiKeys } from "./api/resources/scimApiKeys/client/Client";
import { Sessions } from "./api/resources/sessions/client/Client";
import { UserInvites } from "./api/resources/userInvites/client/Client";
import { Users } from "./api/resources/users/client/Client";

export declare namespace TesseralClient {
    export interface Options {
        environment?: core.Supplier<environments.TesseralEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        backendApiKey?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class TesseralClient {
    protected _organizations: Organizations | undefined;
    protected _passkeys: Passkeys | undefined;
    protected _projects: Projects | undefined;
    protected _samlConnections: SamlConnections | undefined;
    protected _scimApiKeys: ScimApiKeys | undefined;
    protected _sessions: Sessions | undefined;
    protected _userInvites: UserInvites | undefined;
    protected _users: Users | undefined;

    constructor(protected readonly _options: TesseralClient.Options = {}) {}

    public get organizations(): Organizations {
        return (this._organizations ??= new Organizations(this._options));
    }

    public get passkeys(): Passkeys {
        return (this._passkeys ??= new Passkeys(this._options));
    }

    public get projects(): Projects {
        return (this._projects ??= new Projects(this._options));
    }

    public get samlConnections(): SamlConnections {
        return (this._samlConnections ??= new SamlConnections(this._options));
    }

    public get scimApiKeys(): ScimApiKeys {
        return (this._scimApiKeys ??= new ScimApiKeys(this._options));
    }

    public get sessions(): Sessions {
        return (this._sessions ??= new Sessions(this._options));
    }

    public get userInvites(): UserInvites {
        return (this._userInvites ??= new UserInvites(this._options));
    }

    public get users(): Users {
        return (this._users ??= new Users(this._options));
    }
}
