/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const TesseralEnvironment = {
    Default: "https://api.tesseral.com",
} as const;

export type TesseralEnvironment = typeof TesseralEnvironment.Default;
